voxel_grid_filter:
  ros__parameters:
    inputs.cloud.topic: "/points/raw"
    outputs.cloud.topic: "/points/voxelized"
    outputs.indices.topic: "/points/voxelized_indices"
    queue_size: 5
    filter:
      leaf_size_x: 0.05
      leaf_size_y: 0.05
      leaf_size_z: 0.05
      output_indices: false
      invert: false

passthrough_filter:
  ros__parameters:
    inputs.cloud.topic: "/points/voxelized"
    outputs.cloud.topic: "/points/passthrough"
    outputs.indices.topic: "/points/passthrough_indices"
    queue_size: 5
    filter:
      field_name: "z"
      min_value: -1.0
      max_value: 2.0
      output_indices: false
      invert: false

crop_box_filter:
  ros__parameters:
    inputs.cloud.topic: "/points/passthrough"
    outputs.cloud.topic: "/points/filtered"
    outputs.indices.topic: "/points/filtered_indices"
    queue_size: 5
    filter:
      min_x: -10.0
      min_y: -10.0
      min_z: -2.0
      max_x: 10.0
      max_y: 10.0
      max_z: 3.0
      output_indices: false
      invert: false
